# Load Libraries

```{r}
library(tidyverse)
library(here)
```

# Load data

```{r}
long_data <- read_csv(here("data/03_dat_aug_02.csv"))
```

```{r}
selected_genes <- long_data |> 
  slice(1:280) |> # select the first 28 genes
  mutate(
    count_cat = case_when( # create new category for pre and post
      grepl("^pre", count_type) ~ "Pre", 
      grepl("^post", count_type) ~ "Post"
      )
    ) 

```

# Plot

```{r}

# create scatter plot
ggplot(selected_genes, aes(x = name, y = count_value, color = count_cat)) +
  geom_point(size = 5, shape = 21) +
  geom_point(aes(y = filtered_mean_pre), shape = 3, color = "darkblue", size =1) +  # Add pre means
  geom_point(aes(y = filtered_mean_post), shape = 4, color = "darkred", size = 1) +
  labs(
    title = "Scatter Plot of Pre and Post Counts",
    x = "Gene",
    y = "Count",
    color = "Pre/Post"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7)
  ) +
    scale_y_continuous(
    limits = c(0, 500)  # Set the y-axis range between 0 and 500
  )


  ggsave("04_key_plot_1.png", width = 8, height = 6, dpi = 300)

        
```
